name: Django CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Cria um container Postgres exclusivo para o teste
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: db_testes
          POSTGRES_USER: usuario_teste
          POSTGRES_PASSWORD: senha_teste
        ports:
          - 5432:5432
        # Healthcheck para garantir que o banco subiu antes de rodar os testes
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Poetry
      run: pip install poetry

    - name: Instalar Dependências
      run: poetry install --no-root

    - name: Rodar Testes
      env:
        # Usamos as credenciais definidas no 'services' acima
        POSTGRES_DB: db_testes
        POSTGRES_USER: usuario_teste
        POSTGRES_PASSWORD: senha_teste
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        SECRET_KEY: 'chave-secreta-para-testes-ci'
        DEBUG: 'False'
      run: |
        poetry run python manage.py test
